// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foytvhasbjqtdvvkiftd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZveXR2aGFzYmpxdGR2dmtpZnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODM4MDYsImV4cCI6MjA2NDQ1OTgwNn0.WXwxmU_0k834rcqpSaEMCeIz-zcoLRD7vRfC6sSuVO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);